language: node_js
node_js:
  - "10"
  - "11"
cache: yarn
services:
  - docker
before_install:
  - sudo apt-get install libsecret-1-dev
script:
  # Test the subgraph against graph-node
  - ./node_modules/.bin/graph test "yarn test"
